[package]
name = "alias"
version = "2.0.0"
authors = ["wordijp <wordijp@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.4"
lazy_static = "1.4.0"
clap = "2.33.0"
encoding_rs = "0.8.22"
termcolor = "1.1"
atty = "0.2"
mrusty = { git = "https://github.com/wordijp/mrusty" }
